FROM python:3.11-slim

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit psycopg2-binary python-dotenv pandas plotly

COPY . .

EXPOSE 8501

CMD ["streamlit", "run", "interface/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]